### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#100]
10-12 01:02:31.870 15123 15123 E AndroidRuntime: FATAL EXCEPTION: main
10-12 01:02:31.870 15123 15123 E AndroidRuntime: Process: org.glucosio.android, PID: 15123
10-12 01:02:31.870 15123 15123 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment.setData(OverviewFragment.java:174)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment.access$000(OverviewFragment.java:32)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment$1.onItemSelected(OverviewFragment.java:87)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.widget.AdapterView.fireOnSelected(AdapterView.java:924)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:913)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.widget.AdapterView.-wrap1(AdapterView.java)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:883)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-12 01:02:31.870 15123 15123 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: FATAL EXCEPTION: main
10-12 01:03:52.589 15276 15276 E AndroidRuntime: Process: org.glucosio.android, PID: 15276
10-12 01:03:52.589 15276 15276 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment.setData(OverviewFragment.java:168)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment.access$000(OverviewFragment.java:32)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at org.glucosio.android.fragment.OverviewFragment$1.onItemSelected(OverviewFragment.java:87)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.widget.AdapterView.fireOnSelected(AdapterView.java:924)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:913)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.widget.AdapterView.-wrap1(AdapterView.java)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:883)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-12 01:03:52.589 15276 15276 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bkerensa** [comment]
Not sure why this is silently crashing but noticed this when I dumped my logs looking for another app crash.
